/* File produced with RAWTEX Gimp plugin v1.06
   Written by Franck Charlet. */

#define BOX_SIDE_O_TEXTURE_WIDTH 64
#define BOX_SIDE_O_TEXTURE_REAL_WIDTH 64
#define BOX_SIDE_O_TEXTURE_HEIGHT 32
#define BOX_SIDE_O_TEXTURE_REAL_HEIGHT 32
#define BOX_SIDE_O_TEXTURE_FORMAT 4
#define BOX_SIDE_O_TEXTURE_MIPMAPS 0
#define BOX_SIDE_O_TEXTURE_SWIZZLE 1

#define BOX_SIDE_O_PALETTE_FORMAT 3
#define BOX_SIDE_O_PALETTE_COLORS (16 / 8)
#define BOX_SIDE_O_PALETTE_MASK 0xf
#define BOX_SIDE_O_MIPMAPS_OFFSET0 0
