/* File produced with RAWTEX Gimp plugin v1.06
   Written by Franck Charlet. */

#define CONS5NNY3_TEXTURE_WIDTH 64
#define CONS5NNY3_TEXTURE_REAL_WIDTH 64
#define CONS5NNY3_TEXTURE_HEIGHT 64
#define CONS5NNY3_TEXTURE_REAL_HEIGHT 64
#define CONS5NNY3_TEXTURE_FORMAT 4
#define CONS5NNY3_TEXTURE_MIPMAPS 0
#define CONS5NNY3_TEXTURE_SWIZZLE 1

#define CONS5NNY3_PALETTE_FORMAT 3
#define CONS5NNY3_PALETTE_COLORS (16 / 8)
#define CONS5NNY3_PALETTE_MASK 0xf
#define CONS5NNY3_MIPMAPS_OFFSET0 0
