/* File produced with RAWTEX Gimp plugin v1.06
   Written by Franck Charlet. */

#define GROUND_HB3_TEXTURE_WIDTH 128
#define GROUND_HB3_TEXTURE_REAL_WIDTH 128
#define GROUND_HB3_TEXTURE_HEIGHT 128
#define GROUND_HB3_TEXTURE_REAL_HEIGHT 128
#define GROUND_HB3_TEXTURE_FORMAT 4
#define GROUND_HB3_TEXTURE_MIPMAPS 0
#define GROUND_HB3_TEXTURE_SWIZZLE 1

#define GROUND_HB3_PALETTE_FORMAT 3
#define GROUND_HB3_PALETTE_COLORS (16 / 8)
#define GROUND_HB3_PALETTE_MASK 0xf
#define GROUND_HB3_MIPMAPS_OFFSET0 0
