/* File produced with RAWTEX Gimp plugin v1.06
   Written by Franck Charlet. */

#define M_CUPB_FRONT_TEXTURE_WIDTH 32
#define M_CUPB_FRONT_TEXTURE_REAL_WIDTH 32
#define M_CUPB_FRONT_TEXTURE_HEIGHT 32
#define M_CUPB_FRONT_TEXTURE_REAL_HEIGHT 32
#define M_CUPB_FRONT_TEXTURE_FORMAT 4
#define M_CUPB_FRONT_TEXTURE_MIPMAPS 0
#define M_CUPB_FRONT_TEXTURE_SWIZZLE 1

#define M_CUPB_FRONT_PALETTE_FORMAT 3
#define M_CUPB_FRONT_PALETTE_COLORS (16 / 8)
#define M_CUPB_FRONT_PALETTE_MASK 0xf
#define M_CUPB_FRONT_MIPMAPS_OFFSET0 0
