/* File produced with RAWTEX Gimp plugin v1.06
   Written by Franck Charlet. */

#define M_METAL_DARKBLU_TEXTURE_WIDTH 64
#define M_METAL_DARKBLU_TEXTURE_REAL_WIDTH 64
#define M_METAL_DARKBLU_TEXTURE_HEIGHT 64
#define M_METAL_DARKBLU_TEXTURE_REAL_HEIGHT 64
#define M_METAL_DARKBLU_TEXTURE_FORMAT 4
#define M_METAL_DARKBLU_TEXTURE_MIPMAPS 0
#define M_METAL_DARKBLU_TEXTURE_SWIZZLE 1

#define M_METAL_DARKBLU_PALETTE_FORMAT 3
#define M_METAL_DARKBLU_PALETTE_COLORS (16 / 8)
#define M_METAL_DARKBLU_PALETTE_MASK 0xf
#define M_METAL_DARKBLU_MIPMAPS_OFFSET0 0
