/* File produced with RAWTEX Gimp plugin v1.06
   Written by Franck Charlet. */

#define NDU_DOORS_64_TEXTURE_WIDTH 64
#define NDU_DOORS_64_TEXTURE_REAL_WIDTH 64
#define NDU_DOORS_64_TEXTURE_HEIGHT 64
#define NDU_DOORS_64_TEXTURE_REAL_HEIGHT 64
#define NDU_DOORS_64_TEXTURE_FORMAT 4
#define NDU_DOORS_64_TEXTURE_MIPMAPS 0
#define NDU_DOORS_64_TEXTURE_SWIZZLE 1

#define NDU_DOORS_64_PALETTE_FORMAT 3
#define NDU_DOORS_64_PALETTE_COLORS (16 / 8)
#define NDU_DOORS_64_PALETTE_MASK 0xf
#define NDU_DOORS_64_MIPMAPS_OFFSET0 0
