/* File produced with RAWTEX Gimp plugin v1.06
   Written by Franck Charlet. */

#define NDUWALL_TEXTURE_WIDTH 128
#define NDUWALL_TEXTURE_REAL_WIDTH 128
#define NDUWALL_TEXTURE_HEIGHT 128
#define NDUWALL_TEXTURE_REAL_HEIGHT 128
#define NDUWALL_TEXTURE_FORMAT 4
#define NDUWALL_TEXTURE_MIPMAPS 0
#define NDUWALL_TEXTURE_SWIZZLE 1

#define NDUWALL_PALETTE_FORMAT 3
#define NDUWALL_PALETTE_COLORS (16 / 8)
#define NDUWALL_PALETTE_MASK 0xf
#define NDUWALL_MIPMAPS_OFFSET0 0
