/* File produced with RAWTEX Gimp plugin v1.06
   Written by Franck Charlet. */

#define RUST_2_TEXTURE_WIDTH 64
#define RUST_2_TEXTURE_REAL_WIDTH 64
#define RUST_2_TEXTURE_HEIGHT 64
#define RUST_2_TEXTURE_REAL_HEIGHT 64
#define RUST_2_TEXTURE_FORMAT 4
#define RUST_2_TEXTURE_MIPMAPS 0
#define RUST_2_TEXTURE_SWIZZLE 1

#define RUST_2_PALETTE_FORMAT 3
#define RUST_2_PALETTE_COLORS (16 / 8)
#define RUST_2_PALETTE_MASK 0xf
#define RUST_2_MIPMAPS_OFFSET0 0
