/* File produced with RAWTEX Gimp plugin v1.06
   Written by Franck Charlet. */

#define W_S_WOODEN_B64_TEXTURE_WIDTH 64
#define W_S_WOODEN_B64_TEXTURE_REAL_WIDTH 64
#define W_S_WOODEN_B64_TEXTURE_HEIGHT 32
#define W_S_WOODEN_B64_TEXTURE_REAL_HEIGHT 32
#define W_S_WOODEN_B64_TEXTURE_FORMAT 4
#define W_S_WOODEN_B64_TEXTURE_MIPMAPS 0
#define W_S_WOODEN_B64_TEXTURE_SWIZZLE 1

#define W_S_WOODEN_B64_PALETTE_FORMAT 3
#define W_S_WOODEN_B64_PALETTE_COLORS (16 / 8)
#define W_S_WOODEN_B64_PALETTE_MASK 0xf
#define W_S_WOODEN_B64_MIPMAPS_OFFSET0 0
