/* File produced with RAWTEX Gimp plugin v1.06
   Written by Franck Charlet. */

#define W_WOOD_BROWN_RE_TEXTURE_WIDTH 64
#define W_WOOD_BROWN_RE_TEXTURE_REAL_WIDTH 64
#define W_WOOD_BROWN_RE_TEXTURE_HEIGHT 64
#define W_WOOD_BROWN_RE_TEXTURE_REAL_HEIGHT 64
#define W_WOOD_BROWN_RE_TEXTURE_FORMAT 4
#define W_WOOD_BROWN_RE_TEXTURE_MIPMAPS 0
#define W_WOOD_BROWN_RE_TEXTURE_SWIZZLE 1

#define W_WOOD_BROWN_RE_PALETTE_FORMAT 3
#define W_WOOD_BROWN_RE_PALETTE_COLORS (16 / 8)
#define W_WOOD_BROWN_RE_PALETTE_MASK 0xf
#define W_WOOD_BROWN_RE_MIPMAPS_OFFSET0 0
